### ISSUE TITLE
[POST/PUT Property] id not present in the self field

### ISSUE THREAD

**Issue by datanel** [CanalTP/Chaos#189] opened 2016-05-03 08:28 UTC
### Problem about the self field

On method GET /properties/<id>
I have the correct json returned : 

```json
{
  "property": {
    "created_at": "2016-04-13T12:04:17Z",
    "id": "d8beee08-016f-11e6-b540-0050568c8382",
    "key": "special3",
    "self": {
      "href": "http://127.0.0.1:5000/properties/d8beee08-016f-11e6-b540-0050568c8382"
    },
    "type": "comment",
    "updated_at": "2016-04-13T13:31:08Z"
  }
}
```

But with PUT and POST methods, the "self" key in the returned JSON is not complete : 

```json
{
  "property": {
    "created_at": "2016-04-13T12:04:17Z",
    "id": "d8beee08-016f-11e6-b540-0050568c8382",
    "key": "special3",
    "self": {
      "href": "http://127.0.0.1:5000/properties"
    },
    "type": "comment"
  }
}
```

**Comment by eturck** [comment] 2016-06-08 11:58
Have you found the issue? I don't remember exactly but there was maybe a similar problem on the messages too?
If you have found the problem but doesn't have time to fix it we're open to fix it ourselves, we just don't know what to fix yet :).

**Comment by datanel** [comment] 2016-06-08 12:17
we have not found a solution yet. 
we really don't understand why it does not work.

**Comment by eturck** [comment] 2016-06-09 10:10
We spent a bit of time with @vpassama on this. We found the cause, and it's quite tricky!

### 1. SQLAlchemy internals
First, there is a bit of background knowledge to have about SQLAlchemy. Mainly on the commit. Here is a piece of [the doc about commit](http://docs.sqlalchemy.org/en/latest/orm/session_basics.html#committing)
> Another behavior of commit() is that by default it expires the state of all instances present after the commit is complete.

What does it do exactly? Each SQLAlchemy object has a dict attribute where it stores every fields of the object requested in the current session. When you commit, the dict is expired and emptied. It will be filled again the next time you access the object. [More info on this page](http://docs.sqlalchemy.org/en/latest/orm/session_state_management.html#refreshing-expiring)

### 2. Flask Restful internals
Now let's take a look at what we have in chaos. When we're doing a "put" on a property or a category, the last lines of the code when there is no error are : 
```python
db.session.commit()
return marshal({'property': property}, one_property_fields), 200
# Or return marshal({'category': category}, one_category_fields), 200 for a category
```

Then marshal will loop on every one_property_fields or one_category_fields, calling the proper output function for each field.
The field we're are interested in, is a special Flask Restful field, fields.Url : 
```python
'self': {'href': fields.Url('property', absolute=True)},
```

In fields.Url, the output function is called, and one of the first line of the method is : 
```python
data = to_marshallable_type(obj)
```
fields.Url doesn't really use the object (for us, a SQLAlchemy object instance), but try to convert it to a 'marshallable type'. Here is the method : 
```python
def to_marshallable_type(obj):
    if obj is None:
        return None
    if hasattr(obj, '__marshallable__'):
        return obj.__marshallable__()
    if hasattr(obj, '__getitem__'):
        return obj  # it is indexable it is ok
    return dict(obj.__dict__)
```

You're going to have to trust me but in this case it returns `obj.__dict__`, SQLAlchemy object instance doesn't match with another condition.
What is `obj.__dict__`? For a python class instance it returns all the attributes of the instance in a dictionnary. For a SQLAlchemy instance it's similar to the dict storing all the attributes.

### 3. What is the problem?

The problem is between those two libs. We are doing a commit, the object `__dict__` is cleared. If you print `property.__dict__` after the commit you have :
 ```python
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x3cd0c90>}
```

If you access the object directly, by printing or reading one of this attribute, if you print `property.__dict__` again, this time you have : 
 ```python
{'_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x3c19b90>, 'client_id': '9dbf2fa4-86d0-11e4-b461-f01faf2a7e2a', 'key': u'ogive', 'created_at': datetime.datetime(2016, 6, 8, 15, 0, 1, 134540), 'type': u'TEST3', 'updated_at': datetime.datetime(2016, 6, 8, 15, 39, 58, 193155), 'id': 'aca02454-2d89-11e6-97b0-005056bc74dd'}
 ```

As we can see, using `__dict__` doesn't trigger the reloading of the object because it's an internal feature of Python, so SQLAlchemy doesn't have a way to trigger the lazy loading when restful access to `__dict__`, it completely bypass the class methods.

And fields.Url need the __dict__ to be full, because it's calling url_for. And it's doing : 
```python
url_for(self.endpoint, _external = self.absolute, **data))
```
Passing **data (which is obj.__dict__) allow us to match a Url with parameters. If it's empty, it's getting the url for properties, if it's not, there is a key 'id' in the dictionnary, so it can give us the full URL with the /id.

### 4. But... why does it work on another object?

That's the part we had trouble finding out. And that's because there is another parameter, more random.
When we declare the one_(category|property)_fields, we're doing : 
```python
category_fields = {
    'id': fields.Raw,
    'name': fields.Raw,
    'created_at': FieldDateTime,
    'updated_at': FieldDateTime,
    'self': {'href': fields.Url('category', absolute=True)}
}
```

It's a standard python dict. But when we print the dict of fields, when calling marshal, we can see a big difference between the property and the category : 
```python
# property
{
    'self': {
        'href': < flask_restful.fields.Url object at 0x3754390 >
    },
    'updated_at': < class 'chaos.fields.FieldDateTime' > ,
    'id': < class 'flask_restful.fields.Raw' > ,
    'key': < class 'flask_restful.fields.Raw' > ,
    'type': < class 'flask_restful.fields.Raw' > ,
    'created_at': < class 'chaos.fields.FieldDateTime' >
}
# category
{
    'updated_at': < class 'chaos.fields.FieldDateTime' > ,
    'created_at': < class 'chaos.fields.FieldDateTime' > ,
    'id': < class 'flask_restful.fields.Raw' > ,
    'self': {
        'href': < flask_restful.fields.Url object at 0x3754050 >
    },
    'name': < class 'flask_restful.fields.Raw' >
}
```

A python dict doesn't keep the order of the keys. Internally it's ordered by a hash computed by python. That's why OrderedDict exists when you need to keep the key order.
As we can see, for a property, the first field passing in marshal is the Url, for a category it's updated_at.
And when marshalling the Url, we don't trigger the lazy loading because we're using obj.__dict__ instead of the object, but when marshalling another field, it's triggerred.
If the fields.Url is in first, it's not working, if it's after another field triggering the loading, it works.

### 5. Solution?

Good news, there is a solution! We just need to refresh the object in the session.
The question is where and how do we do it : 
- We can bypass the problem by declaring fields in an OrderedDict, making sure the link is at the bottom,
- We can refresh the object in session before calling marshal or after the commit,
- We can set [expire_on_commit at False](http://docs.sqlalchemy.org/en/latest/orm/session_api.html#sqlalchemy.orm.session.Session.params.expire_on_commit) but there is maybe some side effects.

I don't really know what the best solution is. Even on non impacted object it's necessary to refresh because if we rename / add / delete a key on the dictionary of fields it could happen.
I guess for me the best solution would be to call `db.session.refresh(object)` before marshal at the end of each post / put or other method where we just did a db.commit().

@vpassama did I forget something? What do you think is the best and most elegant way to fix this?

**Comment by vpassama** [comment] 2016-06-09 12:15
@eturck, Everything is said and a ` db.session.refresh(object)` seems to be the cleanest/easiest solution for me too. We use to do the same thing with other ORM like doctrine (even if the potential problems aren't the same) and it does the job.

@datanel, that's it ! You can now tell us what do you think about it. I think a global PR is needed on this (not only on property object) because message objects are involved too and you may suffer from it latter if you create new objects.

thanks @eturck for the post ;)

**Comment by vincentlepot** [comment] 2016-07-12 13:45
Very impressive analysis of the bug and the reasons!
Patch is merged.

**Closed** 2016-07-15 08:33 UTC
